// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChdafl7SqryF39g61adG6PyvBCs3Wg2JA',
    appId: '1:552551742254:web:2bfc21ad6359d7d69558bf',
    messagingSenderId: '552551742254',
    projectId: 'new-ecommerce-e42bd',
    authDomain: 'new-ecommerce-e42bd.firebaseapp.com',
    storageBucket: 'new-ecommerce-e42bd.appspot.com',
    measurementId: 'G-S7EJ0TX2RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnwJZr7wVdqWSe6X28f7WHQKiLhvgIOPk',
    appId: '1:552551742254:android:f3e5474da2dfabfb9558bf',
    messagingSenderId: '552551742254',
    projectId: 'new-ecommerce-e42bd',
    storageBucket: 'new-ecommerce-e42bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQxLwaZCwJzPb2X9sR25t7RwUDTw4P4-0',
    appId: '1:552551742254:ios:2640e60579872b4e9558bf',
    messagingSenderId: '552551742254',
    projectId: 'new-ecommerce-e42bd',
    storageBucket: 'new-ecommerce-e42bd.appspot.com',
    iosBundleId: 'com.example.shoppingEcomerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQxLwaZCwJzPb2X9sR25t7RwUDTw4P4-0',
    appId: '1:552551742254:ios:977a95a2af8a51b19558bf',
    messagingSenderId: '552551742254',
    projectId: 'new-ecommerce-e42bd',
    storageBucket: 'new-ecommerce-e42bd.appspot.com',
    iosBundleId: 'com.example.shoppingEcomerce.RunnerTests',
  );
}
