// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBumOqmQS4d1CKbXGmY-iKL47iCoFSyOyE',
    appId: '1:1081077262444:web:26afceeeb0e317f42d5049',
    messagingSenderId: '1081077262444',
    projectId: 'newecommerce-d72c9',
    authDomain: 'newecommerce-d72c9.firebaseapp.com',
    storageBucket: 'newecommerce-d72c9.appspot.com',
    measurementId: 'G-4HV98EDCEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCRocSz6ehrameuKQJfLaisK2M2vo8jHI',
    appId: '1:1081077262444:android:8046acd7dde394342d5049',
    messagingSenderId: '1081077262444',
    projectId: 'newecommerce-d72c9',
    storageBucket: 'newecommerce-d72c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYVfdWKOOJUWDk3yliH0MQGxbHYG9Evfw',
    appId: '1:1081077262444:ios:51cea4af328584ac2d5049',
    messagingSenderId: '1081077262444',
    projectId: 'newecommerce-d72c9',
    storageBucket: 'newecommerce-d72c9.appspot.com',
    iosClientId: '1081077262444-u5mut96dq4su2fm4k515j2vk2jnb10hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYVfdWKOOJUWDk3yliH0MQGxbHYG9Evfw',
    appId: '1:1081077262444:ios:ecebc437fc7a4cbe2d5049',
    messagingSenderId: '1081077262444',
    projectId: 'newecommerce-d72c9',
    storageBucket: 'newecommerce-d72c9.appspot.com',
    iosClientId: '1081077262444-4tuqtf4foqcv1r8qkraos8m4km8nt7mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
